"""
Clinical Intelligence Hub — Alert Addendum Builder

Generates addendum documents when continuous monitoring detects
new findings relevant to the patient (e.g., new drug safety alert,
new clinical trial, updated guidelines).

Each addendum references the original report and explains:
  - What changed
  - Why it matters for this patient
  - What to discuss with the doctor
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from src.models import MonitoringAlert, PatientProfile

logger = logging.getLogger("CIH-Addendum")


class AddendumBuilder:
    """
    Generates alert addendum documents (Word .docx).

    Each addendum is a short document that can be printed
    and brought to a doctor's appointment alongside the main report.
    """

    def generate(self, alert: MonitoringAlert,
                 profile: PatientProfile,
                 output_path: Path) -> Path:
        """
        Generate an addendum document for a monitoring alert.

        Args:
            alert: The monitoring alert to document
            profile: Patient profile for context
            output_path: Where to save the .docx file

        Returns:
            Path to the generated addendum
        """
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError:
            logger.error("python-docx not installed. Run: pip install python-docx")
            raise

        doc = Document()

        # Style
        style = doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(11)

        # Header
        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run("Clinical Intelligence Report — Addendum")
        run.bold = True
        run.font.size = Pt(18)
        run.font.color.rgb = RGBColor(0x1A, 0x47, 0x7A)

        date_p = doc.add_paragraph()
        date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        date_p.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y')}")

        doc.add_paragraph()  # Spacer

        # Alert details
        doc.add_heading("New Finding", level=1)

        severity_label = alert.severity.value.upper()
        p = doc.add_paragraph()
        p.add_run(f"Severity: {severity_label}").bold = True

        doc.add_paragraph()
        doc.add_heading(alert.title, level=2)
        doc.add_paragraph(alert.description)

        # Why it matters
        doc.add_heading("Why This Matters for You", level=2)
        doc.add_paragraph(alert.relevance_explanation)

        # Source
        doc.add_heading("Source", level=2)
        source_text = f"Detected by: {alert.source}"
        if alert.url:
            source_text += f"\nReference: {alert.url}"
        source_text += f"\nDate detected: {alert.date_detected.strftime('%Y-%m-%d')}"
        doc.add_paragraph(source_text)

        # Action
        doc.add_heading("Recommended Action", level=2)
        doc.add_paragraph(
            "Bring this addendum to your next doctor's appointment "
            "and discuss whether this finding affects your current "
            "treatment plan."
        )

        # Disclaimer
        doc.add_paragraph()
        disclaimer = doc.add_paragraph()
        run = disclaimer.add_run(
            "DISCLAIMER: This addendum was generated by an AI monitoring system. "
            "It is NOT medical advice. All findings should be reviewed by a "
            "qualified healthcare provider."
        )
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        # Save
        output_path.parent.mkdir(parents=True, exist_ok=True)
        doc.save(str(output_path))
        logger.info(f"Addendum saved to {output_path}")
        return output_path

    def generate_batch(self, alerts: list[MonitoringAlert],
                       profile: PatientProfile,
                       output_dir: Path) -> list[Path]:
        """
        Generate addendums for multiple alerts.

        Returns list of paths to generated documents.
        """
        paths = []
        for alert in alerts:
            filename = (
                f"addendum_{alert.date_detected.strftime('%Y%m%d')}_"
                f"{alert.source.lower().replace(' ', '_')}.docx"
            )
            path = self.generate(alert, profile, output_dir / filename)
            paths.append(path)
        return paths
