import json
import logging
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import sys

sys.path.append(str(Path(__file__).resolve().parent.parent / "utils"))
from encryption import SecurityManager

logger = logging.getLogger("MedPrep-Report")

class ReportBuilder:
    def __init__(self, profile_path: str, output_dir: str):
        self.profile_path = Path(profile_path)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load the encrypted patient profile
        sm = SecurityManager(self.profile_path.parent)
        self.patient_data = sm.load_profile(self.profile_path) or {}

    def generate_docx(self):
        """Builds the printable Word document intended for the doctor's visit."""
        doc = Document()
        
        # Adjust default styles
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Arial'
        font.size = Pt(11)

        # 1. Title and Metadata
        self._add_header(doc)
        
        # 2. Critical Disclaimer
        self._add_disclaimer(doc)

        # 3. Questions for the Doctor (The most important part, placed up front)
        self._add_questions_section(doc)

        # 4. Patient Community / Anecdotal Correlates
        self._add_community_insights_section(doc)

        # 5. Synthesized Clinical Summary
        self._add_clinical_timeline(doc)

        # Save the file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        output_file = self.output_dir / f"Amaru_MedPrep_Report_{timestamp}.docx"
        doc.save(output_file)
        logger.info(f"Successfully generated Amaru MedPrep Report: {output_file.name}")
        return output_file

    def _add_header(self, doc):
        """Header with patient info and date."""
        heading = doc.add_heading('Amaru MedPrep Patient Summary Report', 0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph(f"Report Generated: {datetime.now().strftime('%B %d, %Y')}")
        doc.add_paragraph("Compiled automatically from decrypted multi-provider medical records.")
        doc.add_page_break()

    def _add_disclaimer(self, doc):
        """The mandatory safety disclaimer."""
        p = doc.add_paragraph()
        run = p.add_run("IMPORTANT: This report was generated by artificial intelligence for informational purposes only. It does not constitute medical advice, diagnosis, or treatment. The analysis may contain errors or miss important context. Always consult your doctor before making any medical decisions. Do not start, stop, or change any medication based on this report.")
        run.bold = True
        run.font.color.rgb = RGBColor(255, 0, 0) # Red
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        doc.add_paragraph() # spacing

    def _add_questions_section(self, doc):
        """
        Extracts the deep-research backed questions.
        This pulls from the Phase 4/5 Deep Research pipeline passing.
        """
        doc.add_heading('Questions for Today\'s Visit', level=1)
        
        questions = self.patient_data.get('ai_analysis', {}).get('questions_for_doctor', [])
        
        if not questions:
            # Mock data if none exist yet
            questions = [
                {
                    "question": "Given my continued dry cough and recent Lisinopril prescription, should we explore an alternative blood pressure medication like an ARB?",
                    "reasoning": "A persistent dry cough is a documented side effect in up to 20% of patients taking ACE inhibitors like Lisinopril.",
                    "citations": "FDA Label Documentation (RxNorm: 20683); Am J Am Heart Assoc. 2021."
                },
                {
                    "question": "Since my A1C reached 6.2% two weeks ago, and my father had Type 2 Diabetes, is it time to discuss early intervention?",
                    "reasoning": "A1C levels between 5.7% and 6.4% indicate prediabetes. Family history significantly increases progression risk.",
                    "citations": "American Diabetes Association (ADA) 2024 Standards of Care."
                }
            ]

        for idx, item in enumerate(questions, 1):
            # The Question
            q_paragraph = doc.add_paragraph()
            q_run = q_paragraph.add_run(f"{idx}. {item['question']}")
            q_run.bold = True
            
            # The Research-Backed Reasoning
            reasoning = doc.add_paragraph("Context/Reasoning: ", style='List Bullet')
            reasoning.add_run(item['reasoning'])
            
            # The Citation
            citation = doc.add_paragraph("Citations: ")
            c_run = citation.add_run(item['citations'])
            c_run.font.size = Pt(9)
            c_run.font.color.rgb = RGBColor(100, 100, 100)
            
            doc.add_paragraph() # Spacing

    def _add_community_insights_section(self, doc):
        """Adds the unverified Reddit/Social listening correlates."""
        insights = self.patient_data.get('ai_analysis', {}).get('community_insights', [])
        
        if not insights:
            return # Don't render the section if no correlates were found
            
        doc.add_page_break()
        doc.add_heading('Patient Experience & Cross-Disciplinary Insights', level=1)
        
        # Mandatory strong disclaimer requested by the spec
        p = doc.add_paragraph()
        run = p.add_run("The following patterns were found in patient community discussions. These are unverified, anecdotal experiences and do not represent established medical consensus. They are provided solely as discussion points for your doctor.")
        run.bold = True
        run.italic = True
        run.font.color.rgb = RGBColor(200, 100, 0) # Orange warning
        
        doc.add_paragraph() # spacing
        
        for idx, item in enumerate(insights, 1):
            q_paragraph = doc.add_paragraph()
            q_run = q_paragraph.add_run(f"Discussion Correlate: {item['medication']} -> '{item['correlated_symptom']}'")
            q_run.bold = True
            
            source = doc.add_paragraph("Source Thread: ", style='List Bullet')
            source.add_run(item['anecdote_title'])
            
            meta = doc.add_paragraph()
            m_run = meta.add_run(f"{item['source']} | Upvotes/Engagement: {item['upvotes']}")
            m_run.font.size = Pt(9)
            m_run.font.color.rgb = RGBColor(100, 100, 100)
            
            doc.add_paragraph()

    def _add_clinical_timeline(self, doc):
        """Append the structured JSON data as readable text."""
        doc.add_page_break()
        doc.add_heading('Clinical Data Overview', level=1)
        
        doc.add_heading('Active Medications', level=2)
        meds = self.patient_data.get('clinical_timeline', {}).get('medications', [])
        for med in meds:
            if med.get('status') == 'active':
                doc.add_paragraph(f"• {med.get('name')} - {med.get('dosage')} (Started: {med.get('start_date')})")
                
        # Space for Labs, Imaging, etc.
        doc.add_paragraph("\n[Detailed Lab and Imaging History omitted for brevity in summary view.]")

if __name__ == "__main__":
    BASE_DIR = Path(__file__).resolve().parent.parent
    PROFILE_PATH = BASE_DIR / "data" / "patient_profile.json"
    OUTPUT_DIR = BASE_DIR / "data" / "processed"
    
    builder = ReportBuilder(PROFILE_PATH, OUTPUT_DIR)
    builder.generate_docx()
